### ISSUE TITLE
Test Mode?

### ISSUE THREAD

**Issue by ryust** [mediavrog/integrated-rating-request#16]
Is there not an easy way to test before the configuration settings apply? I don't know whether my layout is incorrect or whether not enough days/attempts have occurred.

**Comment by mediavrog** [comment]
@ryust Currently there is no dedicated test mode. 

The options I can give you right now is:

1) You can edit the Preferences manually using some buttons as done in the sample app
2) You can provide a custom RuleEngine (https://github.com/mediavrog/integrated-rating-request#custom-rule-engine) which would always show the IRR
3) You can try to change your time settings on your device

As for a dedicated test mode, what output or interaction would you expect?

**Comment by ryust** [comment]
For the output or interaction, just a simple show of the layout as if the process was triggered. At this point I don’t even know if the settings are correct or the layout addition is working… at least show the layout to know it is.

**Comment by mediavrog** [comment]
In your case as for now, the best solution would probably be to initialize it ith a custom rule engine, which would only have one simple rule to always be true 

https://github.com/mediavrog/integrated-rating-request#custom-rule-engine

I might add an option to override the rules and force show of the layout later. PR is also welcome

**Comment by mediavrog** [comment]
closing for now; please reopen if more feedback is needed
