### ISSUE TITLE
Click on Accept Nudge Button triggers onDismiss

### ISSUE THREAD

**Issue by simplysoft** [mediavrog/integrated-rating-request#8]
It looks like this is opposite what you would usually expect?

https://github.com/mediavrog/integrated-rating-request/blob/master/library/src/main/java/net/mediavrog/irr/IrrLayout.java#L308

**Comment by mediavrog** [comment]
Thanks for the find. Will update soon

**Comment by mediavrog** [comment]
Fixed in 1.1.2
